include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-duuJ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: notification-details-fn-8fb550f8-4e7a-45c1-9aec-24542604405e
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-duuJ
  environment:
    name: notification-details-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-09T20:18:45Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: notification-details-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: notification-details-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: notification-details-fn-8fb550f8-4e7a-45c1-9aec-24542604405e
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
