include:
- ./func/*
kind: ArchiveUploadSpec
name: func-PquU

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: notification-details-fn-1caa8e23-b6b2-440b-8269-257d4d01267d
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: notification-details-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-PquU
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-11-29T22:17:51Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: notification-details-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: notification-details-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_notification_details
    packageref:
      name: notification-details-fn-1caa8e23-b6b2-440b-8269-257d4d01267d
      namespace: default
  requestsPerPod: 10000
  resources: {}
